### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by JohanAke1** [jonkristian/mediatracker-ha#3]
Does the integration still work with latest Home Assistant? For me the integration setup just ends in "unknown" error message.
I have tried to input the host and port in every possible way and it does not seem to make a difference. Application token I created in Media Tracker side.

**Comment by jonkristian** [comment]
Hello @JohanAke1. The integration should work with the latest 2024.10.3 version of HA. I am not seing any issues. Can you provide more details about your setup, are both systems on the same lan locally? Have you tried enabling debugging for the integration and checking the logs?

**Comment by davidschinkel** [comment]
I too have problems connecting the integration with my Media-Tracker instance. I hope it is ok to comment on this thread.

I see the following erors in the log:

```log
2025-02-23 13:11:42.971 ERROR (MainThread) [custom_components.mediatracker.config_flow] Unknown error trying to connect
hass               | Traceback (most recent call last):
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1115, in _wrap_create_connection
hass               |     sock = await aiohappyeyeballs.start_connection(
hass               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |     ...<5 lines>...
hass               |     )
hass               |     ^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
hass               |     # If the errno is the same for all exceptions, raise
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
hass               |         )
hass               |     
hass               |         for addrinfo in addr_infos
hass               |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |     ),
hass               |     ^^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
hass               |     except:
hass               |         ^^^
hass               |   File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 641, in sock_connect
hass               |     return await fut
hass               |            ^^^^^^^^^
hass               |   File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 681, in _sock_connect_cb
hass               |     raise OSError(err, f'Connect call failed {address}')
hass               | OSError: [Errno 113] Connect call failed ('AAA.BBB.CCC.DDD', 7481)
hass               | 
hass               | The above exception was the direct cause of the following exception:
hass               | 
hass               | Traceback (most recent call last):
hass               |   File "/config/custom_components/mediatracker/config_flow.py", line 68, in async_step_user
hass               |     info = await validate_input(self.hass, user_input)
hass               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |   File "/config/custom_components/mediatracker/config_flow.py", line 34, in validate_input
hass               |     config = await mediatracker.get_config()
hass               |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |   File "/usr/local/lib/python3.13/site-packages/pymediatracker/__init__.py", line 91, in get_config
hass               |     response: ClientResponse = await self._client.get(
hass               |                                ^^^^^^^^^^^^^^^^^^^^^^^
hass               |         f"http://{self._host}/api/configuration?token={self._token}"
hass               |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |     )
hass               |     ^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 703, in _request
hass               |     conn = await self._connector.connect(
hass               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |         req, traces=traces, timeout=real_timeout
hass               |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |     )
hass               |     ^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 548, in connect
hass               |     proto = await self._create_connection(req, traces, timeout)
hass               |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1056, in _create_connection
hass               |     _, proto = await self._create_direct_connection(req, traces, timeout)
hass               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1400, in _create_direct_connection
hass               |     raise last_exc
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1369, in _create_direct_connection
hass               |     transp, proto = await self._wrap_create_connection(
hass               |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hass               |     ...<7 lines>...
hass               |     )
hass               |     ^
hass               |   File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1130, in _wrap_create_connection
hass               |     raise client_error(req.connection_key, exc) from exc
hass               | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host AAA.BBB.CCC.DDD:7481 ssl:default [Connect call failed ('AAA.BBB.CCC.DDD', 7481)]
```

The (Docker) Home-Assistant-Instance and the Media-Tracker-Instance are runnig on the same Raspberry-Pi and have different ip-Adresses through macvlan.

Inside Media-Tracker I see the following log
```
mediatracker  | error: AxiosError: Request failed with status code 400
mediatracker  |     at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
mediatracker  |     at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:382:11)
mediatracker  |     at IncomingMessage.emit (node:events:530:35)
mediatracker  |     at endReadableNT (node:internal/streams/readable:1698:12)
mediatracker  |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by jonkristian** [comment]
Hello. No worries. 

Can you try running network mode host and use the lan ip:port directly? If it's just one raspberry pi with these two services you'd probably be better off just using the host network? Never used macvlan so not sure if that is the issue, but i suspect it could be. If you can't do that, can you try reaching mediatracker via terminal in ha? It clearly says: `Cannot connect to host AAA.BBB.CCC.DDD:7481`

**Comment by davidschinkel** [comment]
Thanks for your fast response. I could indeed not reach the ip from within the home-assistant instance running in host mode. After changing the MediaTracker instance to host mode too, everything works fine.
Thanks a lot for your help.

**Comment by jonkristian** [comment]
Nice! You're welcome.
